import { test, expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';

test('profile imports without blocking and syncs a new Drive PDF while on Notes', async ({ page }) => {
  const pdf = await PDFDocument.create(); pdf.addPage();
  const bytes = Buffer.from(await pdf.save());
  let added = false;
  let release!: () => void;
  const downloadGate = new Promise<void>(resolve => { release = resolve; });
  const folder = { id: 'books', name: 'Books', mimeType: 'application/vnd.google-apps.folder' };
  const file = (id: string) => ({ id, name: `${id}.pdf`, mimeType: 'application/pdf', size: String(bytes.length), modifiedTime: '2026-09-01T00:00:00Z' });
  await page.route('**/api/auth/status', route => route.fulfill({ json: { configured: true, persistent: true, connected: true, accountId: 'account', email: 'reader@example.com' } }));
  await page.route('**/api/drive/**', async route => {
    const url = new URL(route.request().url());
    if (url.pathname.endsWith('/changes/startPageToken')) return route.fulfill({ json: { startPageToken: '0' } });
    if (url.pathname.endsWith('/changes')) return route.fulfill({ json: { changes: added ? [{ fileId: 'added', file: { ...file('added'), parents: ['books'] } }] : [], newStartPageToken: added ? '1' : '0' } });
    if (url.searchParams.get('alt') === 'media') { await downloadGate; return route.fulfill({ contentType: 'application/pdf', body: bytes }); }
    if (url.pathname.endsWith('/books')) return route.fulfill({ json: folder });
    if (url.pathname.endsWith('/first')) return route.fulfill({ json: file('first') });
    if (url.pathname.endsWith('/added')) return route.fulfill({ json: file('added') });
    return route.fulfill({ json: { files: url.searchParams.get('q')?.startsWith("'root'") ? [folder] : added ? [file('first'), file('added')] : [file('first')] } });
  });
  await page.clock.install();
  await page.goto('/');
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await expect(page.getByText('Connected: reader@example.com')).toBeVisible();
  await expect(page.getByLabel('Folder name', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/drive-profile.png' });
  await page.getByRole('button', { name: 'Choose a Drive folder' }).click();
  await page.locator('.drive-folder-list').getByRole('button', { name: 'Books', exact: true }).click();
  await page.getByRole('button', { name: 'Import this Drive folder' }).click();
  await expect(page.locator('.drive-connection')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'View Drive sync status' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Notes', exact: true })).toBeVisible();
  await expect(page.locator('.drive-sync-toast')).toHaveCount(0);
  const syncButton = page.getByRole('button', { name: 'View Drive sync status' });
  expect((await syncButton.boundingBox())!.width).toBeGreaterThanOrEqual(44);
  await syncButton.click();
  await expect(page.locator('.profile-folder-row')).toContainText('Syncing');
  await expect(page.locator('.profile-folder-row .folder-sync-dot')).not.toHaveClass(/is-synced/);
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  release();
  const count = () => page.evaluate(() => JSON.parse(localStorage.getItem('minotes-v1')!).state.readDocuments.length);
  await expect.poll(count).toBe(1);
  await expect(page.getByRole('button', { name: 'View Drive sync status' })).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await expect(page.locator('.profile-folder-row')).toContainText('Synced');
  await expect(page.locator('.profile-folder-row .folder-sync-dot')).toHaveClass(/is-synced/);
  await page.screenshot({ path: 'test-results/profile-sync-status.png' });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Read', exact: true }).click();
  const refreshBox = await page.getByRole('button', { name: 'Refresh connected folders', exact: true }).boundingBox();
  expect(refreshBox!.width).toBeGreaterThanOrEqual(44);
  expect(refreshBox!.height).toBeGreaterThanOrEqual(44);
  await page.getByRole('button', { name: 'Notes', exact: true }).click();
  added = true;
  await page.clock.fastForward(31000);
  await expect.poll(count).toBe(2);
  await expect(page.getByRole('heading', { name: 'Notes', exact: true })).toBeVisible();
});
